version: '3.3'
services: 

  appFrontend:
    build:
      dockerfile: ./deploy/Dockerfile
      context: ./
    container_name: rentMovieApp
    image: frontend/rentmovieapp
    command: bash -c "npm install && npm run dev"
    user: root
    ports: 
      - 5173:5173
    volumes: 
      - ./:/app
    restart: always